apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
    name: read-file
spec:
  params:
    - name: filename
      type: string
      description: name of file in workspace to print content of
      default: "message.txt"
  results:
    - name: output
      description: the content of params.filename
  steps:
    - name: write
      image: registry.access.redhat.com/ubi9/ubi-minimal@sha256:3685c58885771d2ea14608caeab6a4c3949b973588c29ce91f462b486ee1be25
      env:
        - name: MESSAGE_PATH
          value: $(workspaces.input.path)/$(params.filename)
        - name: OUTPUT_PATH
          value: $(results.output.path)
      script: |
        #!/usr/bin/env bash
        cat "$MESSAGE_PATH" | tee "$OUTPUT_PATH"
  workspaces:
    - name: input
      description: The folder where the params.file is stored
      mountPath: /workspace/output
