apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: write-read-run-
spec:
  pipelineRef:
    name: write-read
  params:
    - name: username
      value: World!
  workspaces:
    - name: pipeline-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Mi
