apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: read
spec:
  workspaces:
    - name: source
      description: source directory where to read text
      mountPath: /read
  steps:
    - name: read
      image: registry.access.redhat.com/ubi9/ubi-minimal@sha256:3685c58885771d2ea14608caeab6a4c3949b973588c29ce91f462b486ee1be25
      env:
      - name: TEXT_PATH
        value: $(workspaces.source.path)/text
      script: |
        #!/bin/sh
        cat ${TEXT_PATH}
